#Redisson配置
singleServerConfig:
  address: "redis://127.0.0.1:6379"
  clientName: back
  database: 10
  idleConnectionTimeout: 10000
  connectTimeout: 100000
  timeout: 30000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"